package it.polimi.ingsw.psp23.model.enumeration;

public enum GameStatus {
    Setup,
    Building,
    CheckBoards,
    Playing,
    End,
    INIT_ABANDONEDSHIP,
    INIT_PLANETS,
    INIT_ABANDONEDSTATION,
    INIT_COMBATZONE,
    INIT_EPIDEMIC,
    INIT_METEORSWARM,
    INIT_OPENSPACE,
    INIT_PIRATES,
    INIT_SLAVERS,
    INIT_SMUGGLERS,
    INIT_STARDUST,
    END_ABANDONEDSTATION,
    END_ABANDONEDSHIP,
    END_PLANETS,
    END_COMBATZONE,
    END_EPIDEMIC,
    END_METEORSWARM,
    END_OPENSPACE,
    END_PIRATES,
    END_SLAVERS,
    END_SMUGGLERS,
    END_STARDUST,
    BooleanRequest,
    IntegerRequest,
    RunningEpidemic,
    RunningMeteorSwarm,
    ChooseCabins,
    RunningOpenSpace,
    RunningPlanets,
    RunningSlavers,
    //aggiungere altri stati
}
